name: elcueapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  cloud_firestore: ^5.0.2
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  image_picker: ^1.1.2
  fluttertoast: ^8.2.6
  intl: ^0.19.0
  agora_rtc_engine: ^6.3.2
  firebase_messaging: ^15.0.2
  permission_handler: ^9.0.2
  flutter_local_notifications: ^17.2.1
  speech_to_text: ^6.6.2
  camera: ^0.11.0+1
  tflite: ^1.1.2
  path_provider: ^2.1.3
  path: ^1.9.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/google_logo.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Italic.ttf
          style: italic
